#pragma once

#define CHUNK_LENGTH 16
#define CHUNK_AREA (CHUNK_LENGTH * CHUNK_LENGTH)
#define CHUNK_VOLUME (CHUNK_LENGTH * CHUNK_LENGTH * CHUNK_LENGTH)

#define VOXEL_SIZE (1.0f)
#define CHUNK_WORLD_LENGTH (CHUNK_LENGTH * VOXEL_SIZE)
#define CHUNK_LOAD_BATCH 8

#define TERRAIN_MAX_HEIGHT 128
#define TERRAIN_GROUND_LEVEL 0