#pragma once

#define CHUNK_LENGTH 32
#define CHUNK_AREA (CHUNK_LENGTH * CHUNK_LENGTH)
#define CHUNK_VOLUME (CHUNK_LENGTH * CHUNK_LENGTH * CHUNK_LENGTH)

#define VOXEL_SIZE (1.0f / 8.0f)
#define TERRAIN_MAX_HEIGHT (CHUNK_LENGTH * 8)