#pragma once

#define VULKAN_HPP_NO_STRUCT_CONSTRUCTORS

#define APPLICATION_NAME "Vanguard"
#define WINDOW_NAME APPLICATION_NAME

#define FRAMES_IN_FLIGHT 2
#define FRAMES_IN_FLIGHT_PLUS_ONE (FRAMES_IN_FLIGHT + 1)